use super::{v, vh, Item, Lesson};

const fn lesson(
    episode: u16,
    korean: &'static str,
    meaning: &'static str,
    vocab: &'static [Item],
    grammar: &'static [Item],
) -> Lesson {
    Lesson {
        series_n: 2,
        episode,
        series: "참교육",
        korean,
        meaning,
        vocab,
        grammar,
    }
}

pub const LESSONS: &[Lesson] = &[
    lesson(
        0,
        "본 작품은 가상으로 만들어진 허구의 이야기입니다",
        "This work is a fictional story created as fiction.",
        &[
            vh("본", "本", "this / the present"),
            vh("작품", "作品", "work (of art)"),
            vh("가상", "假想", "fiction / imagination"),
            v("만들다", "to make"),
            vh("허구", "虛構", "fiction"),
            v("이야기", "story"),
        ],
        &[
            v("작품은", "작품 + 은 (topic)"),
            v("가상으로", "가상 + 으로 (as / by means of)"),
            v("만들어진", "만들 + 어지다 + ㄴ (that was made)"),
            v("허구의", "허구 + 의 (of fiction)"),
            v("이야기입니다", "이야기 + 이다 + ㅂ니다 (is a story)"),
        ],
    ),
    lesson(
        1,
        "2011년 체벌금지법의 통과 이후",
        "After the 2011 ban on corporal punishment passed.",
        &[
            vh("2011년", "年", "the year 2011"),
            vh("체벌", "體罰", "corporal punishment"),
            vh("금지법", "禁止法", "a ban / prohibition law"),
            vh("통과", "通過", "passage / passing"),
            vh("이후", "以後", "after / since"),
        ],
        &[
            v("2011년", "2011 + 년 (year)"),
            v("체벌금지법의", "체벌금지법 + 의 (of the ban)"),
            v("통과 이후", "after the passage"),
        ],
    ),
    lesson(
        2,
        "교사들은 원칙적으로 더 이상 학생에게 매를 드는 일이 금지되었다",
        "In principle, teachers were no longer allowed to hit students.",
        &[
            vh("교사", "敎師", "teacher"),
            vh("원칙", "原則", "principle"),
            v("더 이상", "no longer"),
            vh("학생", "學生", "student"),
            v("매", "a rod / a cane"),
            v("들다", "to raise / to take up"),
            v("일", "act / matter"),
            vh("금지", "禁止", "prohibition"),
        ],
        &[
            v("교사들은", "교사 + 들 + 은 (teachers, topic)"),
            v("원칙적으로", "원칙 + 적 + 으로 (in principle)"),
            v("더 이상", "더 + 이상 (no longer)"),
            v("학생에게", "학생 + 에게 (to a student)"),
            v("매를", "매 + 를 (the rod, object)"),
            v("드는", "들다 + 는 (that raises)"),
            v("일이", "일 + 이 (the act, subject)"),
            v("금지되었다", "금지되다 + 었 + 다 (was prohibited)"),
        ],
    ),
    lesson(
        3,
        "체벌금지법 도입 이후 교사들은 학생들을 지도하기 대단히 어려워졌다",
        "After the corporal-punishment ban, teachers found it much harder to guide students.",
        &[
            vh("체벌금지법", "體罰禁止法", "corporal-punishment ban"),
            vh("도입", "導入", "introduction"),
            vh("이후", "以後", "after / since"),
            vh("교사", "敎師", "teacher"),
            vh("학생", "學生", "students"),
            vh("지도", "指導", "guidance"),
            v("대단히", "greatly / very much"),
            v("어렵다", "to be difficult"),
        ],
        &[
            v("체벌금지법", "체벌 + 금지 + 법 (the ban)"),
            v("도입 이후", "도입 + 이후 (after the introduction)"),
            v("교사들은", "교사 + 들 + 은 (teachers, topic)"),
            v("학생들을", "학생 + 들 + 을 (students, object)"),
            v("지도하기", "지도하다 + 기 (guiding, nominal)"),
            v("대단히", "greatly"),
            v("어려워졌다", "어렵다 + 어지다 + 었 + 다 (became difficult)"),
        ],
    ),
    lesson(
        4,
        "학생들이 마음놓고 교권을 침해하는 행동을 하여도 이를 제재할 수단이 그다지 많지 않았던 것이다",
        "Even if students freely violated teachers' authority, there were not that many ways to sanction it.",
        &[
            vh("학생", "學生", "student"),
            v("마음", "heart / mind"),
            v("놓다", "to put / to let"),
            vh("교권", "敎權", "teachers' authority"),
            vh("침해", "侵害", "violation"),
            vh("행동", "行動", "behavior / act"),
            vh("제재", "制裁", "sanction"),
            vh("수단", "手段", "means"),
            v("그다지", "not that / not so"),
            v("많다", "to be many"),
        ],
        &[
            v("학생들이", "학생 + 들 + 이 (students, subject)"),
            v("마음놓고", "마음 + 놓다 + 고 (freely, at ease)"),
            v("교권을", "교권 + 을 (authority, object)"),
            v("침해하는", "침해하다 + 는 (that violates)"),
            v("행동을", "행동 + 을 (the act, object)"),
            v("하여도", "하다 + 여도 (even if one does)"),
            v("이를", "이 + 를 (this, object)"),
            v("제재할", "제재하다 + ㄹ (to sanction)"),
            v("수단이", "수단 + 이 (a means, subject)"),
            v("그다지", "not that"),
            v("많지 않았던", "많다 + 지 않다 + 았 + 던 (that were not many)"),
            v("것이다", "것 + 이다 (it is the case)"),
        ],
    ),
    lesson(
        5,
        "학생들은 어른의 생각보다 영악하였고",
        "The students were more cunning than adults expected, and",
        &[
            vh("학생", "學生", "student"),
            v("어른", "adult"),
            v("생각", "thought / expectation"),
            vh("영악하다", "靈惡", "cunning"),
        ],
        &[
            v("학생들은", "학생 + 들 + 은 (students, topic)"),
            v("어른의", "어른 + 의 (of adults)"),
            v("생각보다", "생각 + 보다 (than one thinks)"),
            v("영악하였고", "영악하다 + 였 + 고 (were cunning, and)"),
        ],
    ),
    lesson(
        6,
        "전 그 학생 머리카락 하나 건드린 적 없습니다! 그런데 제가 왜",
        "I've never so much as touched that student's hair! So why am I",
        &[
            v("저", "I"),
            v("그", "that"),
            vh("학생", "學生", "student"),
            v("머리카락", "hair"),
            v("하나", "one / a single"),
            v("건드리다", "to touch / to mess with"),
            v("적", "an occasion / ever"),
            v("없다", "to not exist"),
            v("그런데", "but / so"),
            v("왜", "why"),
        ],
        &[
            v("전", "저 + ㄴ (I, topic)"),
            v("그 학생", "그 + 학생 (that student)"),
            v("머리카락", "hair"),
            v("하나", "하나 (a single)"),
            v("건드린 적", "건드리 + ㄴ 적 (ever touched)"),
            v("없습니다", "없다 + 습니다 (there is not)"),
            v("그런데", "but / so"),
            v("제가", "저 + 가 (I, subject)"),
            v("왜", "why"),
        ],
    ),
    lesson(
        7,
        "법을 자신에게 유리하게 이용할 줄 알았다",
        "They knew how to use the law to their own advantage.",
        &[
            vh("법", "法", "law"),
            vh("자신", "自身", "oneself"),
            vh("유리하다", "有利", "advantageous"),
            vh("이용하다", "利用", "to use"),
            v("줄", "how to / the know-how"),
            v("알다", "to know"),
        ],
        &[
            v("법을", "법 + 을 (the law, object)"),
            v("자신에게", "자신 + 에게 (to oneself)"),
            v("유리하게", "유리하다 + 게 (advantageously)"),
            v("이용할 줄", "이용하다 + ㄹ 줄 (how to use)"),
            v("알았다", "알다 + 았 + 다 (knew)"),
        ],
    ),
    lesson(
        8,
        "전국 교사 1,196명을 대상으로 앙케이트 조사를 한 결과",
        "The result of a survey of 1,196 teachers nationwide.",
        &[
            vh("전국", "全國", "the whole country"),
            vh("교사", "敎師", "teacher"),
            v("1,196명", "1,196 people"),
            vh("대상", "對象", "target / subject"),
            v("앙케이트", "questionnaire"),
            vh("조사", "調査", "survey"),
            v("하다", "to do"),
            vh("결과", "結果", "result"),
        ],
        &[
            v("전국 교사", "전국 + 교사 (teachers nationwide)"),
            v("1,196명을", "1,196 + 명 + 을 (1,196 people, object)"),
            v("대상으로", "대상 + 으로 (as the target)"),
            v("앙케이트 조사", "앙케이트 + 조사 (a questionnaire survey)"),
            v("조사를", "조사 + 를 (the survey, object)"),
            v("한", "하다 + ㄴ (that was done)"),
            v("결과", "결과 (result)"),
        ],
    ),
    lesson(
        9,
        "과거보다 학생 지도가 어려워졌다는 비율이 98.6%⋯ 매우 어려워졌다는 비율이 85.8%에 달하였다.",
        "The share who said guiding students got harder than in the past was 98.6%… the share who said it got much harder reached 85.8%.",
        &[
            vh("과거", "過去", "the past"),
            vh("학생", "學生", "student"),
            vh("지도", "指導", "guidance"),
            v("어렵다", "to be difficult"),
            vh("비율", "比率", "share / ratio"),
            v("매우", "very"),
            v("달하다", "to reach"),
        ],
        &[
            v("과거보다", "과거 + 보다 (than in the past)"),
            v("학생 지도가", "학생 지도 + 가 (guiding students, subject)"),
            v("어려워졌다는", "어렵다 + 어지다 + 었 + 다는 (that it became difficult)"),
            v("비율이", "비율 + 이 (the share, subject)"),
            v("98.6%", "98.6 percent"),
            v("매우", "very"),
            v("85.8%에", "85.8% + 에 (at 85.8%)"),
            v("달하였다", "달하다 + 였 + 다 (reached)"),
        ],
    ),
    lesson(
        10,
        "교권, 교실 붕괴의 문제가 나날이 지적되던 어느 날⋯",
        "One day, as the collapse of teacher authority and the classroom was pointed out more every day…",
        &[
            vh("교권", "敎權", "teacher authority"),
            vh("교실", "敎室", "classroom"),
            vh("붕괴", "崩壞", "collapse"),
            vh("문제", "問題", "problem"),
            v("나날이", "day by day"),
            vh("지적", "指摘", "pointing out"),
            v("어느", "a certain / some"),
            v("날", "day"),
        ],
        &[
            v("교권", "교권 (teacher authority)"),
            v("교실 붕괴의", "교실 붕괴 + 의 (of classroom collapse)"),
            v("문제가", "문제 + 가 (the problem, subject)"),
            v("나날이", "나날이 (day by day)"),
            v("지적되던", "지적 + 되다 + 던 (that kept being pointed out)"),
            v("어느 날", "어느 + 날 (one day)"),
        ],
    ),
    lesson(
        11,
        "급기야 교사 한 명이 수업 시간에 학생에게 폭행 치사를 당한 사건이 벌어진다.",
        "Finally, an incident occurs in which a teacher is beaten to death by a student during class.",
        &[
            v("급기야", "finally / at last"),
            vh("교사", "敎師", "teacher"),
            v("한 명", "one person"),
            vh("수업", "授業", "class"),
            vh("시간", "時間", "time"),
            vh("학생", "學生", "student"),
            vh("폭행", "暴行", "assault"),
            vh("치사", "致死", "causing death"),
            v("당하다", "to suffer / to be subjected to"),
            vh("사건", "事件", "incident"),
            v("벌어지다", "to happen / to break out"),
        ],
        &[
            v("급기야", "급기야 (finally)"),
            v("교사 한 명이", "교사 + 한 명 + 이 (one teacher, subject)"),
            v("수업 시간에", "수업 시간 + 에 (during class)"),
            v("학생에게", "학생 + 에게 (by a student)"),
            v("폭행 치사를", "폭행 치사 + 를 (assault causing death, object)"),
            v("당한", "당하다 + ㄴ (that was suffered)"),
            v("사건이", "사건 + 이 (the incident, subject)"),
            v("벌어진다", "벌어지다 + ㄴ다 (occurs)"),
        ],
    ),
    lesson(
        12,
        "한 톱스타의 스캔들로 인해",
        "Because of a top star's scandal,",
        &[
            v("한", "one"),
            v("톱스타", "a top star"),
            v("스캔들", "a scandal"),
            v("인하다", "to be due to"),
        ],
        &[
            v("한", "한/MM (one)"),
            v("톱스타의", "톱스타/NNG + 의/JKG (of a top star)"),
            v("스캔들로 인해", "스캔들/NNG + 로/JKB + 인하/VV + 여/EC (because of a scandal)"),
        ],
    ),
];
