use super::{v, vh, Item, Lesson};

const fn lesson(
    episode: u16,
    korean: &'static str,
    meaning: &'static str,
    vocab: &'static [Item],
    grammar: &'static [Item],
) -> Lesson {
    Lesson {
        series_n: 2,
        episode,
        series: "참교육",
        korean,
        meaning,
        vocab,
        grammar,
    }
}

pub const LESSONS: &[Lesson] = &[
    lesson(
        0,
        "본 작품은 가상으로 만들어진 허구의 이야기입니다",
        "This work is a fictional story created as fiction.",
        &[
            vh("본", "本", "this / the present"),
            vh("작품", "作品", "work (of art)"),
            vh("가상", "假想", "fiction / imagination"),
            v("만들다", "to make"),
            vh("허구", "虛構", "fiction"),
            v("이야기", "story"),
        ],
        &[
            v("작품은", "작품 + 은 (topic)"),
            v("가상으로", "가상 + 으로 (as / by means of)"),
            v("만들어진", "만들 + 어지다 + ㄴ (that was made)"),
            v("허구의", "허구 + 의 (of fiction)"),
            v("이야기입니다", "이야기 + 이다 + ㅂ니다 (is a story)"),
        ],
    ),
    lesson(
        1,
        "2011년 체벌금지법의 통과 이후",
        "After the 2011 ban on corporal punishment passed.",
        &[
            vh("2011년", "年", "the year 2011"),
            vh("체벌", "體罰", "corporal punishment"),
            vh("금지법", "禁止法", "a ban / prohibition law"),
            vh("통과", "通過", "passage / passing"),
            vh("이후", "以後", "after / since"),
        ],
        &[
            v("2011년", "2011 + 년 (year)"),
            v("체벌금지법의", "체벌금지법 + 의 (of the ban)"),
            v("통과 이후", "after the passage"),
        ],
    ),
    lesson(
        2,
        "교사들은 원칙적으로 더 이상 학생에게 매를 드는 일이 금지되었다",
        "In principle, teachers were no longer allowed to hit students.",
        &[
            vh("교사", "敎師", "teacher"),
            vh("원칙", "原則", "principle"),
            v("더 이상", "no longer"),
            vh("학생", "學生", "student"),
            v("매", "a rod / a cane"),
            v("들다", "to raise / to take up"),
            v("일", "act / matter"),
            vh("금지", "禁止", "prohibition"),
        ],
        &[
            v("교사들은", "교사 + 들 + 은 (teachers, topic)"),
            v("원칙적으로", "원칙 + 적 + 으로 (in principle)"),
            v("더 이상", "더 + 이상 (no longer)"),
            v("학생에게", "학생 + 에게 (to a student)"),
            v("매를", "매 + 를 (the rod, object)"),
            v("드는", "들다 + 는 (that raises)"),
            v("일이", "일 + 이 (the act, subject)"),
            v("금지되었다", "금지되다 + 었 + 다 (was prohibited)"),
        ],
    ),
    lesson(
        3,
        "체벌금지법 도입 이후 교사들은 학생들을 지도하기 대단히 어려워졌다",
        "After the corporal-punishment ban, teachers found it much harder to guide students.",
        &[
            vh("체벌금지법", "體罰禁止法", "corporal-punishment ban"),
            vh("도입", "導入", "introduction"),
            vh("이후", "以後", "after / since"),
            vh("교사", "敎師", "teacher"),
            vh("학생", "學生", "students"),
            vh("지도", "指導", "guidance"),
            v("대단히", "greatly / very much"),
            v("어렵다", "to be difficult"),
        ],
        &[
            v("체벌금지법", "체벌 + 금지 + 법 (the ban)"),
            v("도입 이후", "도입 + 이후 (after the introduction)"),
            v("교사들은", "교사 + 들 + 은 (teachers, topic)"),
            v("학생들을", "학생 + 들 + 을 (students, object)"),
            v("지도하기", "지도하다 + 기 (guiding, nominal)"),
            v("대단히", "greatly"),
            v("어려워졌다", "어렵다 + 어지다 + 었 + 다 (became difficult)"),
        ],
    ),
    lesson(
        4,
        "학생들이 마음놓고 교권을 침해하는 행동을 하여도 이를 제재할 수단이 그다지 많지 않았던 것이다",
        "Even if students freely violated teachers' authority, there were not that many ways to sanction it.",
        &[
            vh("학생", "學生", "student"),
            v("마음", "heart / mind"),
            v("놓다", "to put / to let"),
            vh("교권", "敎權", "teachers' authority"),
            vh("침해", "侵害", "violation"),
            vh("행동", "行動", "behavior / act"),
            vh("제재", "制裁", "sanction"),
            vh("수단", "手段", "means"),
            v("그다지", "not that / not so"),
            v("많다", "to be many"),
        ],
        &[
            v("학생들이", "학생 + 들 + 이 (students, subject)"),
            v("마음놓고", "마음 + 놓다 + 고 (freely, at ease)"),
            v("교권을", "교권 + 을 (authority, object)"),
            v("침해하는", "침해하다 + 는 (that violates)"),
            v("행동을", "행동 + 을 (the act, object)"),
            v("하여도", "하다 + 여도 (even if one does)"),
            v("이를", "이 + 를 (this, object)"),
            v("제재할", "제재하다 + ㄹ (to sanction)"),
            v("수단이", "수단 + 이 (a means, subject)"),
            v("그다지", "not that"),
            v("많지 않았던", "많다 + 지 않다 + 았 + 던 (that were not many)"),
            v("것이다", "것 + 이다 (it is the case)"),
        ],
    ),
    lesson(
        5,
        "학생들은 어른의 생각보다 영악하였고",
        "The students were more cunning than adults expected, and",
        &[
            vh("학생", "學生", "student"),
            v("어른", "adult"),
            v("생각", "thought / expectation"),
            vh("영악하다", "靈惡", "cunning"),
        ],
        &[
            v("학생들은", "학생 + 들 + 은 (students, topic)"),
            v("어른의", "어른 + 의 (of adults)"),
            v("생각보다", "생각 + 보다 (than one thinks)"),
            v("영악하였고", "영악하다 + 였 + 고 (were cunning, and)"),
        ],
    ),
    lesson(
        6,
        "전 그 학생 머리카락 하나 건드린 적 없습니다! 그런데 제가 왜",
        "I've never so much as touched that student's hair! So why am I",
        &[
            v("저", "I"),
            v("그", "that"),
            vh("학생", "學生", "student"),
            v("머리카락", "hair"),
            v("하나", "one / a single"),
            v("건드리다", "to touch / to mess with"),
            v("적", "an occasion / ever"),
            v("없다", "to not exist"),
            v("그런데", "but / so"),
            v("왜", "why"),
        ],
        &[
            v("전", "저 + ㄴ (I, topic)"),
            v("그 학생", "그 + 학생 (that student)"),
            v("머리카락", "hair"),
            v("하나", "하나 (a single)"),
            v("건드린 적", "건드리 + ㄴ 적 (ever touched)"),
            v("없습니다", "없다 + 습니다 (there is not)"),
            v("그런데", "but / so"),
            v("제가", "저 + 가 (I, subject)"),
            v("왜", "why"),
        ],
    ),
    lesson(
        7,
        "법을 자신에게 유리하게 이용할 줄 알았다",
        "They knew how to use the law to their own advantage.",
        &[
            vh("법", "法", "law"),
            vh("자신", "自身", "oneself"),
            vh("유리하다", "有利", "advantageous"),
            vh("이용하다", "利用", "to use"),
            v("줄", "how to / the know-how"),
            v("알다", "to know"),
        ],
        &[
            v("법을", "법 + 을 (the law, object)"),
            v("자신에게", "자신 + 에게 (to oneself)"),
            v("유리하게", "유리하다 + 게 (advantageously)"),
            v("이용할 줄", "이용하다 + ㄹ 줄 (how to use)"),
            v("알았다", "알다 + 았 + 다 (knew)"),
        ],
    ),
];
