use super::{v, vh, Item, Lesson};

const fn lesson(
    episode: u16,
    korean: &'static str,
    meaning: &'static str,
    vocab: &'static [Item],
    grammar: &'static [Item],
) -> Lesson {
    Lesson {
        series_n: 1,
        episode,
        series: "퇴사할게여",
        korean,
        meaning,
        vocab,
        grammar,
    }
}

pub const LESSONS: &[Lesson] = &[
    lesson(
        1,
        "퇴사할게여",
        "I’m gonna quit~",
        &[
            vh("퇴사하다", "退社", "quit a company job"),
            v("−ㄹ게", "I decided / I promise"),
            v("여", "cute 요"),
        ],
        &[v("−ㄹ게여", "−ㄹ게요 with 요 written 여")],
    ),
    lesson(
        2,
        "퇴사할게요",
        "I’ll quit.",
        &[
            vh("퇴사하다", "退社", "to resign"),
            v("−ㄹ게요", "polite promise"),
        ],
        &[v("하 + ㄹ게요", "I will (decision)")],
    ),
    lesson(
        3,
        "아쉬울 거도 없거든요",
        "There’s nothing I’ll even miss, you see.",
        &[
            v("아쉽다", "feel a loss / too bad"),
            v("것", "thing"),
            v("거", "thing (spoken 것)"),
            v("도", "even"),
            v("없다", "not exist / not have"),
            v("−거든요", "because / you see"),
        ],
        &[
            v("아쉬울", "아쉽다 + ㄹ"),
            v("아쉬울 거도 없다", "there isn’t even something to miss"),
            v("없거든요", "there isn’t, you see"),
        ],
    ),
    lesson(
        4,
        "원래 이렇게 열심히",
        "I was never going to live this hard…",
        &[
            vh("원래", "原來", "originally / all along"),
            v("이렇게", "like this"),
            vh("열심히", "熱心", "hard / diligently"),
        ],
        &[v("이렇게 열심히", "this hard (line continues)")],
    ),
    lesson(
        5,
        "살 생각 없었거든요",
        "…I never meant to live like that, you see.",
        &[
            v("살다", "to live"),
            vh("생각", "生覺", "thought / plan"),
            v("없다", "not have"),
            v("−었거든요", "past + you see"),
        ],
        &[
            v("살 생각", "plan to live"),
            v("없었거든요", "I didn’t have, you see"),
        ],
    ),
    lesson(
        6,
        "오래 했어요",
        "I did it for a long time.",
        &[
            v("오래", "for a long time"),
            v("하다", "to do"),
            v("−었어요", "past polite"),
        ],
        &[v("했어요", "did")],
    ),
    lesson(
        7,
        "수백 번을 참았거든요",
        "I held it in hundreds of times, you see.",
        &[
            vh("수백", "數百", "hundreds"),
            vh("번", "番", "times"),
            v("을", "object"),
            v("참다", "endure / hold in"),
            v("−았거든요", "past + you see"),
        ],
        &[
            v("수백 번을", "hundreds of times (object)"),
            v("참았거든요", "I endured, you see"),
        ],
    ),
    lesson(
        8,
        "쿨하게 짐을 싸고 뒤돌아보지 않고",
        "Pack cool, don’t look back.",
        &[
            v("쿨하다", "be cool"),
            v("−게", "adverb"),
            v("짐", "bags / stuff"),
            v("싸다", "to pack"),
            v("−고", "and"),
            v("뒤돌아보다", "look back"),
            v("−지 않고", "without doing"),
        ],
        &[
            v("쿨하게", "coolly"),
            v("싸고", "pack and"),
            v("뒤돌아보지 않고", "without looking back"),
        ],
    ),
    lesson(
        9,
        "모두 안녕히 계세요",
        "Everyone, goodbye. (She’s the one leaving.)",
        &[
            v("모두", "everyone"),
            vh("안녕히", "安寧", "peacefully"),
            v("계세요", "please stay"),
        ],
        &[
            v("안녕히 계세요", "goodbye to people who stay"),
            v("안녕히 가세요", "goodbye to people who leave"),
        ],
    ),
    lesson(
        10,
        "그래 이팔청춘 후회하면 어때요",
        "So what if I regret it while I’m young?",
        &[
            v("그래", "yeah / so"),
            vh("이팔청춘", "二八靑春", "youth (16–25)"),
            vh("후회하다", "後悔", "to regret"),
            v("−면", "if"),
            v("어때요", "so what / how is it"),
        ],
        &[v("후회하면 어때요", "so what if (I) regret")],
    ),
    lesson(
        11,
        "당장 저 문밖으로 떠나요",
        "Leave out that door right now.",
        &[
            vh("당장", "當場", "right away"),
            v("저", "that over there"),
            vh("문", "門", "door"),
            v("밖", "outside"),
            v("−으로", "toward"),
            v("떠나다", "to leave"),
            v("−아요", "polite"),
        ],
        &[
            v("문밖으로", "out the door"),
            v("떠나요", "leave / let’s leave"),
        ],
    ),
    lesson(
        12,
        "날씨 좋군요 바람 좋군요",
        "Oh, the weather’s nice. Oh, the wind’s nice.",
        &[
            v("날씨", "weather"),
            v("좋다", "be good"),
            v("바람", "wind"),
            v("−군요", "I notice"),
        ],
        &[v("좋군요", "oh, it’s nice")],
    ),
    lesson(
        13,
        "결국 우린 모두 할머니가 될 거고",
        "In the end we’ll all be grandmas, and…",
        &[
            vh("결국", "結局", "in the end"),
            v("우리", "we"),
            v("우린", "우리는"),
            v("모두", "all"),
            v("할머니", "grandma"),
            v("가", "subject"),
            v("되다", "become"),
            v("−ㄹ 거고", "will … and"),
        ],
        &[
            v("할머니가 되다", "become a grandma"),
            v("될 거고", "will become, and"),
        ],
    ),
    lesson(
        14,
        "뒤돌아보면 오늘 하루는",
        "When we look back, today…",
        &[
            v("뒤돌아보다", "look back"),
            v("−면", "when / if"),
            v("오늘", "today"),
            v("하루", "a day"),
            v("는", "topic"),
        ],
        &[v("뒤돌아보면", "when (we) look back")],
    ),
    lesson(
        15,
        "밥 먹을까요",
        "Shall we eat?",
        &[
            v("밥", "meal / rice"),
            v("먹다", "eat"),
            v("−ㄹ까요", "shall we?"),
        ],
        &[v("먹을까요", "shall we eat?")],
    ),
    lesson(
        16,
        "요즘 시간 좀 많거든요",
        "I’ve got time these days, you see.",
        &[
            v("요즘", "these days"),
            vh("시간", "時間", "time"),
            v("좀", "a bit"),
            v("많다", "be a lot"),
            v("−거든요", "you see"),
        ],
        &[v("많거든요", "I’ve got a lot, you see")],
    ),
    lesson(
        17,
        "이제 전처럼 절대로 약속 취소할 일은 없죠",
        "I won’t cancel plans like I used to, right?",
        &[
            v("이제", "from now on"),
            vh("전", "前", "before"),
            v("−처럼", "like"),
            vh("절대로", "絕對", "never"),
            vh("약속", "約束", "appointment / plans"),
            vh("취소하다", "取消", "cancel"),
            vh("일", "事", "a case / matter"),
            v("없다", "there isn’t"),
            v("−죠", "right?"),
        ],
        &[
            v("전처럼", "like before"),
            v("취소할 일", "a case of canceling"),
            v("−ㄹ 일은 없죠", "there won’t be any, right?"),
        ],
    ),
    lesson(
        18,
        "너 너 이거 또 거짓말하네",
        "Hey, you’re lying again.",
        &[
            v("너", "you"),
            v("이거", "this"),
            v("또", "again"),
            v("거짓말", "a lie"),
            v("−네", "I notice"),
        ],
        &[v("거짓말하네", "(you’re) lying, I see")],
    ),
    lesson(
        19,
        "여행 갈까요",
        "Shall we travel?",
        &[
            vh("여행", "旅行", "trip"),
            v("가다", "go"),
            v("−ㄹ까요", "shall we?"),
        ],
        &[v("갈까요", "shall we go?")],
    ),
    lesson(
        20,
        "버킷리스트가 있거든요",
        "I’ve got a bucket list, you see.",
        &[
            v("버킷리스트", "bucket list"),
            v("가", "subject"),
            v("있다", "have / there is"),
            v("−거든요", "you see"),
        ],
        &[v("N가 있거든요", "I’ve got N, you see")],
    ),
    lesson(
        21,
        "전 세계 일주하기",
        "Go around the world.",
        &[
            vh("전", "全", "whole"),
            vh("세계", "世界", "world"),
            vh("일주하다", "一周", "go around"),
            v("−기", "verb as noun"),
        ],
        &[v("일주하기", "going around")],
    ),
    lesson(
        22,
        "소설책 작가 되기",
        "Become a novelist.",
        &[
            vh("소설", "小說", "novel"),
            vh("책", "冊", "book"),
            vh("작가", "作家", "writer"),
            v("되다", "become"),
            v("−기", "verb as noun"),
        ],
        &[v("되기", "becoming")],
    ),
    lesson(
        23,
        "맘 편히 노래 부르기",
        "Sing easy.",
        &[
            v("마음", "heart / mind"),
            v("맘", "마음 short"),
            vh("편하다", "便", "comfortable"),
            vh("편히", "便", "at ease"),
            v("노래", "song"),
            v("부르다", "sing"),
            v("−기", "verb as noun"),
        ],
        &[
            v("편히", "comfortably"),
            v("노래 부르기", "singing"),
        ],
    ),
    lesson(
        24,
        "내 이런 철없는 말이",
        "These childish words of mine…",
        &[
            v("내", "my"),
            v("이런", "this kind of"),
            v("철없다", "immature"),
            v("말", "words"),
            v("이", "subject"),
        ],
        &[v("철없는", "childish (modifies 말)")],
    ),
    lesson(
        25,
        "조금 당황스러워도",
        "…even if they throw you a bit.",
        &[
            v("조금", "a little"),
            vh("당황스럽다", "唐慌", "awkward / flustered"),
            v("−어도", "even if"),
        ],
        &[v("당황스러워도", "even if awkward")],
    ),
    lesson(
        26,
        "오늘은 날 잡지는 말아요",
        "Don’t hold me back today.",
        &[
            v("오늘", "today"),
            v("은", "topic"),
            v("날", "me (나를)"),
            v("잡다", "grab / hold back"),
            v("−지 말아요", "please don’t"),
        ],
        &[
            v("날", "나 + 를"),
            v("잡지는 말아요", "don’t hold me back"),
        ],
    ),
    lesson(
        27,
        "언젠가 후회하는 날이 와도",
        "Even if a day of regret comes someday…",
        &[
            v("언젠가", "someday"),
            vh("후회하다", "後悔", "regret"),
            v("날", "day"),
            v("이", "subject"),
            v("오다", "come"),
            v("−아도", "even if"),
        ],
        &[
            v("후회하는 날", "a day of regretting"),
            v("와도", "even if (it) comes"),
        ],
    ),
    lesson(
        28,
        "낭만이라 할 테죠",
        "I’ll still call it romance.",
        &[
            vh("낭만", "浪漫", "romance"),
            v("−이라", "as / called"),
            v("하다", "call / say"),
            v("−ㄹ 테다", "I will / I bet"),
            v("−죠", "you know"),
        ],
        &[
            v("낭만이라 하다", "call it romance"),
            v("할 테죠", "I will (treat it as that)"),
        ],
    ),
    lesson(
        29,
        "나는 낭만적인 할머니가 되어서",
        "I’ll be a romantic grandma, and then…",
        &[
            v("나", "I"),
            v("는", "topic"),
            vh("낭만적인", "浪漫的", "romantic"),
            v("할머니", "grandma"),
            v("되다", "become"),
            v("−어서", "and then"),
        ],
        &[
            v("−적인", "−ic"),
            v("되어서", "become and then"),
        ],
    ),
    lesson(
        30,
        "뒤돌아보곤 오늘 하루를",
        "I’d look back on this one day.",
        &[
            v("뒤돌아보다", "look back"),
            v("−곤", "used to / would"),
            v("오늘", "today"),
            v("하루", "a day"),
            v("를", "object"),
        ],
        &[
            v("뒤돌아보곤", "would look back"),
            v("오늘 하루를", "today’s one day (object)"),
        ],
    ),
];
